"""
Unit tests for the permissions-global Alembic chain (work unit 1.5,
alembic-2fast change).

No PostgreSQL and no database are required:

1. The chain shim (``migrations/permissions-global/env.py``) exists and
   dispatches to the shared async env shipped by
   ``pgsqlasync2fast_fastapi.migrations``.
2. Importing ``permissions2fast_fastapi`` registers the permissions
   ``ChainSpec`` under the ``"auth"`` lane with the exact shipping contract.
3. The AUTH lane is FK-proven ordered: oauth first, then permissions-global.
4. The autogenerated baseline ``0001_initial`` is parseable via
   ``ScriptDirectory`` (zero DB), creates exactly the seven owned RBAC
   tables, never the foreign ``users`` table, and keeps the cross-chain FK
   ``role_users.user_id -> users.id``.
5. The whole chain renders to SQL in alembic OFFLINE mode through the shared
   env (shim dispatch -> offline configure with literal_binds).

Run with: uv run pytest tests/test_migration_chains.py -v
"""

from __future__ import annotations

import os
from importlib import resources

os.environ.setdefault("SECRET_KEY", "test-secret-key-not-for-production")

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from pgsqlasync2fast_fastapi import get_lane_chains

import permissions2fast_fastapi  # noqa: F401  (side effect: registers chain)

SCRIPT_LOCATION = "permissions2fast_fastapi:migrations/permissions-global"

OWNED = frozenset(
    {
        "roles",
        "permissions",
        "permission_categories",
        "routes",
        "role_users",
        "permission_assignments",
        "permission_routes",
    }
)


def _permissions_spec():
    chains = get_lane_chains("auth")
    own = [c for c in chains if c.package == "permissions2fast_fastapi"]
    assert len(own) == 1, f"expected exactly one permissions chain, got {len(own)}"
    return own[0]


def test_chain_shim_exists_and_dispatches_to_shared_env():
    shim = (
        resources.files("permissions2fast_fastapi")
        / "migrations"
        / "permissions-global"
        / "env.py"
    )
    assert shim.is_file()
    text = shim.read_text()
    assert "pgsqlasync2fast_fastapi.migrations" in text
    assert "run_migrations_offline" in text
    assert "run_migrations_online" in text
    assert "context.is_offline_mode()" in text


def test_permissions_chain_registered_in_auth_lane_with_contract():
    spec = _permissions_spec()
    assert spec.package == "permissions2fast_fastapi"
    assert spec.script_path == "migrations/permissions-global"
    assert spec.version_table == "alembic_version_permissions"
    assert spec.owned_tables == OWNED


def test_auth_lane_orders_oauth_before_permissions():
    # FK-proven order (design D6): oauth -> permissions-global ->
    # tenant2fast-auth. When installed together, oauth2fast registers its
    # chain at import time, so the oauth spec must precede the permissions
    # spec in the auth lane.
    chains = get_lane_chains("auth")
    assert chains
    assert next(c.package for c in chains) == "oauth2fast_fastapi"
    assert _permissions_spec() in chains


def test_permissions_chain_target_metadata_is_shared_with_oauth():
    spec = _permissions_spec()
    # permissions models inherit AuthModel -> tables live in oauth2fast's
    # metadata (design D9 shared MetaData), partitioned by owned_tables.
    assert "users" in spec.target_metadata.tables
    assert "roles" in spec.target_metadata.tables


def test_baseline_0001_initial_parseable_and_owns_exactly_seven_tables():
    cfg = Config()
    cfg.set_main_option("script_location", SCRIPT_LOCATION)
    script = ScriptDirectory.from_config(cfg)

    head = script.get_current_head()
    assert head == "0001"
    rev = script.get_revision(head)
    assert rev.down_revision is None  # single-baseline chain

    filepath = rev.path
    assert filepath.endswith("0001_initial.py"), filepath

    with open(filepath) as fh:
        text = fh.read()
    for table in sorted(OWNED):
        assert f"op.create_table('{table}'" in text
    # Ownership boundary: the foreign users table must NOT be proposed.
    assert "op.create_table('users'" not in text
    # Alembic renders third-party types module-qualified without importing
    # the module (alembic 1.20.0 _repr_type); the baseline must carry it.
    assert "import sqlmodel" in text
    # Cross-chain FK (FK-proven order): role_users references users.id even
    # though users belongs to the oauth chain.
    assert "['users.id']" in text


def test_chain_upgrades_to_head_in_offline_mode():
    # Executes the chain shim -> shared runner env offline path: the whole
    # chain (env + versions) renders SQL without any database. Proves the
    # shim imports resolve and the baseline is loadable by alembic.
    cfg = Config()
    cfg.set_main_option("script_location", SCRIPT_LOCATION)
    cfg.set_main_option(
        "sqlalchemy.url", "postgresql+asyncpg://u:p@h:5432/authdb"
    )
    cfg.set_main_option("version_table", "alembic_version_permissions")
    cfg.attributes["target_metadata"] = _permissions_spec().target_metadata

    command.upgrade(cfg, "head", sql=True)