"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-17 07:30:18.796135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_categories_id'), 'permission_categories', ['id'], unique=False)
    op.create_index(op.f('ix_permission_categories_name'), 'permission_categories', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permission_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_category_id'], ['permission_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('role_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_role_users_id'), 'role_users', ['id'], unique=False)
    op.create_index(op.f('ix_role_users_role_id'), 'role_users', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_users_user_id'), 'role_users', ['user_id'], unique=False)
    op.create_table('permission_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id', 'entity_type', 'entity_id', name='uq_permission_assignment')
    )
    op.create_index(op.f('ix_permission_assignments_entity_id'), 'permission_assignments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_permission_assignments_entity_type'), 'permission_assignments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_permission_assignments_id'), 'permission_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_permission_assignments_permission_id'), 'permission_assignments', ['permission_id'], unique=False)
    op.create_table('permission_routes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id', 'route_id', name='uq_permission_route')
    )
    op.create_index(op.f('ix_permission_routes_id'), 'permission_routes', ['id'], unique=False)
    op.create_index(op.f('ix_permission_routes_permission_id'), 'permission_routes', ['permission_id'], unique=False)
    op.create_index(op.f('ix_permission_routes_route_id'), 'permission_routes', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_routes_route_id'), table_name='permission_routes')
    op.drop_index(op.f('ix_permission_routes_permission_id'), table_name='permission_routes')
    op.drop_index(op.f('ix_permission_routes_id'), table_name='permission_routes')
    op.drop_table('permission_routes')
    op.drop_index(op.f('ix_permission_assignments_permission_id'), table_name='permission_assignments')
    op.drop_index(op.f('ix_permission_assignments_id'), table_name='permission_assignments')
    op.drop_index(op.f('ix_permission_assignments_entity_type'), table_name='permission_assignments')
    op.drop_index(op.f('ix_permission_assignments_entity_id'), table_name='permission_assignments')
    op.drop_table('permission_assignments')
    op.drop_index(op.f('ix_role_users_user_id'), table_name='role_users')
    op.drop_index(op.f('ix_role_users_role_id'), table_name='role_users')
    op.drop_index(op.f('ix_role_users_id'), table_name='role_users')
    op.drop_table('role_users')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permission_categories_name'), table_name='permission_categories')
    op.drop_index(op.f('ix_permission_categories_id'), table_name='permission_categories')
    op.drop_table('permission_categories')
    # ### end Alembic commands ###
